version: "3"
services:

  redis:
    image: redis:7.0.2
    ports:
      - "6379:6379"

  jaeger:
    image: jaegertracing/all-in-one:1.35.1
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
      COLLECTOR_ZIPKIN_HOST_PORT: ":9411"
    ports:
      - "4317:4317"
      - "4318:4318"
      - "9411:9411"
      - "14250:14250"
      - "16686:16686"
